name = "mole"

[dependencies]
armadillo-code = {git = "https://gitlab.com/rouson/armadillo-code.git", tag = "fpm"}
julienne = {git = "https://github.com/berkeleylab/julienne.git", tag = "3.6.0"}

[install]
library = true
